name: EndthePortal
version: @version@
main: dev.the456gamer.EndthePortal.EndthePortal
api-version: 1.21.11
authors: [The456gamer]
description: Stops End dimension exit portal from being entered.
website: https://github.com/mrfdev/EndthePortal
